title: Hubbing.net
url: "http://hubbing.net"
baseurl:
google_analytics_key: UA-129612620-1
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Education for everybody by spreading experiential learning.

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  linkedin: # linkedin username

# Social details for the jekyll-seo-tag gem
social:
  name: Hubbing.net
  links:
  - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  team:
    output: true
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team-member"
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Twitter

